language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- cd functions
before_deploy:
- cd $TRAVIS_BUILD_DIR/functions
script:
- npm run lint
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: NNVEDDGEmiLtNMqFgoHQnTGCRZF+KGPtQ/MA0jlts8bHQQnAeIo8qqFptQzfce3La4khzxi4rKbkVM/ShfCVvNj8aTIa3+PTeDoBcdLmsZzA5tL13k8FIbmgwYD8P846oJCGWoqElU75JvhHqS2AYTPBWWoDXr2nVTBD43/ijmxZ8SW5ct0iRFy79RWcwHPZb9DnZ2dvjRQaH6fuDtIkKieN5OSvuyGazeN3qDygahOS1FCCqabGfsHt+OmZeiQ3oEfuqEBV4fbQgFTpryt7SBS4ps9tpWlIQ9hvULjcNsXVyXhqOZPMX5s5wjfNGxkA7uvMjF3Wa/AUPXPNNbLDVZkpQ2V04EsPyX3wD5u13L5jXeEVgD8wyxJX1+48eNgF2sMs5E58KyG0SaCFS2uveyNqGZ8RnuF7vNLSRJjfHNS0OqsB/inWF0ysMFa/zdPoB2cOjoo8ZO5QXpaDpAAQ2xfAxfFKW3UvXDXCVauxhoMml6kEvALDNF8Pn0vzxlCAcfNN1+5blws5ljQ6cJkvH8jpmLv+pshD0UDADsysygHxWYmGJNRnJEzNmkAGGHDUXi7OCXKuIEgPacA0REycuxZcocWAdoE9VOzBNnlAvMV2sDEK+3oTPa5rK76N7GJmP1mdcGwdl8FMy3n8CxX5Vqa8ovsTT6FbfaixQ7fV6vU=